# Generated by Django 3.2.4 on 2021-06-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Places',
            new_name='Place',
        ),
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
